function [interaction_list, head] = readFinalInteractionList(fn)
%READFINALINTERACTIONLIST Reads interaction list output by Interactions module.
%   [list,head]=READFINALINTERACTIONLIST(fn) reads the list of predicted 
%   interactions fn generated by INTERACTIONS. Corresponds to
%   writeOutput_interactions. head is the header of fn. list is a structure 
%   with fields:
%
%   list.data      Nx5 matrix corresponding to N predicted interactions.
%                  Columns are both proteins in reference? (logical),
%                  interaction in reference? (logical), average interaction
%                  probability across conditions, average interaction score
%                  across conditions, interaction score per condition.
%   list.textdata  Nx3 cell array of text data from fn. Columns are
%                  interaction, protein A, protein B.
%
%   See also PRINCE, INTERACTIONS.


column_names1 = {'Unique interactions','Protein A','Protein B','Center A',...
  'Center B','Replicate','Channel','Delta Center','R^2',...
  'Euc. Dist', 'Both proteins in Corum', 'Interaction in Corum','Interaction score',...
  'Score rank (low = better)','Score percentile (low = better)','Precision level',...
  'Global?'};

column_names2 = {'Unique interactions','Protein A', 'Protein B','Replicate',...
  'Channel','Both proteins in Corum','Interaction in Corum','Interaction score',...
  'Score rank (low = better)','Score percentile (low = better)','Precision level'};

column_names3 = {'Unique interactions','Protein A', 'Protein B',...
  'Channel','Both proteins in Corum','Interaction in Corum','Interaction score',...
  'Score rank (low = better)','Score percentile (low = better)','Precision level'};

column_names4 = { 'Unique interactions','Protein A','Protein B','Channel',...
  'Both proteins in Corum', 'Interaction in Corum','Score (avg.)',...
  'Precision (avg.)','Precision (condition-specific)'};

fid = fopen(fn);

header = fgetl(fid);
header = strsplit(header,',');
header(cellfun('isempty',header)) = [];

if isequal(header,column_names1)
  Idata = [11 12 13 14 15 16 17];
  Itext = [1 2 3 4 5 6 7 8 9 10];
elseif isequal(header,column_names2)
  Idata = [6 7 8 9 10 11];
  Itext = [1 2 3 4 5];
elseif isequal(header,column_names3)
  Idata = [5 6 7 8 9 10];
  Itext = [1 2 3 4];
elseif isequal(header,column_names4)
  Idata = [5 6 7 8 9];
  Itext = [1 2 3 4];
else
  error('Incorrectly formatted Final_Interactions_list')
end
head.data = header(Idata);
head.text = header(Itext);

interaction_list.data = nan(200000,length(Idata));
interaction_list.text = cell(200000,length(Itext));
cc = 0;
while ~feof(fid)
  
  current_line = fgetl(fid);
  current_line = strsplit(current_line,',');
  cc = cc+1;
  
  for ii = 1:length(Idata)
    interaction_list.data(cc,ii) = str2double(current_line{Idata(ii)});
  end
  for ii = 1:length(Itext)
    interaction_list.text{cc,ii} = current_line{Itext(ii)};
  end
end

interaction_list.data = interaction_list.data(1:cc,:);
interaction_list.text = interaction_list.text(1:cc,:);
