

% #output
%Write out comparsion of gaussian in biological replicate
s = [datadir '/Final_2foldchange_list_between_' user.comparisonpairs{1} 'and' user.comparisonpairs{2} '.csv'];
fid_combined_gaus_with_changes_output= fopen(s,'wt'); % create the output file with the header infromation
fprintf (fid_combined_gaus_with_changes_output,'%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n',... %header for OutputGaus output
  'Protein name', 'Replicate', 'Height', 'Center', 'Width', 'adjrsquare','Observed in channel','Changes Observed',...
  'Fold Change (based on raw data)','Normalise Fold Change (based on raw data)'); %Write Header
for writeout_counter1= 1:number_of_proteins
  fprintf(fid_combined_gaus_with_changes_output,'%s,%d,%6.3f,%6.3f,%6.3f,%6.3f,%6.3f,%s,%s,%6.4f,%6.4f,\n',...
    Combined_Gaussians.Protein_name{writeout_counter1},...
    Combined_Gaussians.Replicate(writeout_counter1),...
    Combined_Gaussians.Height(writeout_counter1),...
    Combined_Gaussians.Center(writeout_counter1),...
    Combined_Gaussians.Width(writeout_counter1),...
    Combined_Gaussians.adjrsquare(writeout_counter1),...
    Combined_Gaussians.Channels{writeout_counter1},...
    Combined_Gaussians.Observed_change{writeout_counter1},...
    Combined_Gaussians.log2_of_gaussians(writeout_counter1),...
    Combined_Gaussians.log2_normalised_gaussians(writeout_counter1));
  %Combined_Gaussians.Area_of_combined_gaussian(writeout_counter1),...
  %Combined_Gaussians.Precentage_combined(writeout_counter1),...
end
fclose(fid_combined_gaus_with_changes_output);


% #output
%Write out trend observed in gaussian grouped by proteins and replicate
fid_summed_area= fopen([datadir '/Final_2foldchange_trends_' user.comparisonpairs{1} 'and' user.comparisonpairs{2} '.csv'],'wt'); % create the output file with the header infromation
fprintf (fid_summed_area,'%s,%s,%s,%s,%s\n',... %header for OutputGaus output
  'Protein name', 'Replicate', 'Number of gaussians observed','Observed change',' Were changes consistent across all guassians'); %Write Header
for writeout_counter1= 1:NuniqueGauss
  fprintf(fid_summed_area,'%s,%d,%6.3f,%s,%s,\n',...
    GaussSummary(1).Protein_name{writeout_counter1},...
    GaussSummary(1).Replicate(writeout_counter1,1),...
    Ngaussperrep_prot(writeout_counter1),...
    trendString{writeout_counter1,1},...
    trendString{writeout_counter1,2});
  %Combined_Gaussians.Summed_MvsL_area(writeout_counter1,1),...
  %Combined_Gaussians.Summed_HvsL_area(writeout_counter1,1),...
  %Combined_Gaussians.Summed_Precentage_MvsL(writeout_counter1,1),...
  %Combined_Gaussians.Summed_Precentage_HvsL(writeout_counter1,1),...
end
fclose(fid_summed_area);


% #output
%Write table of is gaussian were fitted in the HvsL and/or MvsL
s = [datadir '/Gaussian_list.csv'];
fid_combined_gaus_output= fopen(s,'wt'); % create the output file with the header infromation
fprintf (fid_combined_gaus_output,'%s,%s,%s,%s,%s,%s,%s,%s\n',... %header for OutputGaus output
  'Protein name','Replicate','Complex Size', 'Height', 'Center', 'Width', 'adjrsquare','Observed in channel'); %Write Header
for writeout_counter1= 1:number_of_proteins
  fprintf(fid_combined_gaus_output,'%s,%d,%6.3f,%6.3f,%6.3f,%6.3f,%6.3f,%s,\n',...%6.3f,%6.3f,%6.3f,%6.3f,%6.3f,%6.3f,\n',...
    Combined_Gaussians.Protein_name{writeout_counter1},...
    Combined_Gaussians.Replicate(writeout_counter1),...
    Combined_Gaussians.Complex_size(writeout_counter1),...
    Combined_Gaussians.Height(writeout_counter1),...
    Combined_Gaussians.Center(writeout_counter1),...
    Combined_Gaussians.Width(writeout_counter1),...
    Combined_Gaussians.adjrsquare(writeout_counter1),...
    Combined_Gaussians.Channels{writeout_counter1});
  %Combined_Gaussians.Area_of_combined_gaussian(writeout_counter1,writeout_counter2),...
  %Combined_Gaussians.Area_of_MvsL_gaussian(writeout_counter1,writeout_counter2),...
  %Combined_Gaussians.Area_of_HvsL_gaussian(writeout_counter1,writeout_counter2),...
  %Combined_Gaussians.Precentage_combined(writeout_counter1,writeout_counter2),...
  %Combined_Gaussians.Precentage_MvsL(writeout_counter1,writeout_counter2),...
  %Combined_Gaussians.Precentage_HvsL(writeout_counter1,writeout_counter2));
end
fclose(fid_combined_gaus_output);


fid_Summary_gaussian= fopen([datadir '/Summary_gaussians_detected_between_replicates.csv'],'wt'); % create the summary file of the interaction output
fprintf (fid_Summary_gaussian,'%s,','Total gaussians');
for ci = 1:Nchannels
  fprintf(fid_Summary_gaussian,'%s,',['Gaussians within ' Experimental_channels{ci} ' channel']);
end
fprintf(fid_Summary_gaussian,'%s,%s,%s,%s,%s,\n',...
  'Shared Gaussians','Number of Gaussians that increase', 'Number of Gaussians that decrease',....
  'Number of Gaussians that do not change','Number of Unquantified');
fprintf(fid_Summary_gaussian,'%6.4f,',number_of_proteins);
for ci = 1:Nchannels
  fprintf(fid_Summary_gaussian,'%6.4f,',Unique_gaussians_in_eachchannel(ci));
end
fprintf(fid_Summary_gaussian,'%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,\n',...
  shared_gaussian_counter, sum(Iinc), sum(Idec), sum(~Idec & ~Iinc), sum(Ibad));


% fid_Summary_gaussian= fopen([datadir 'Comparison/Summary_gaussian_detected_between_replicates.csv'],'wt'); % create the summary file of the interaction output
% fprintf (fid_Summary_gaussian,'%s,','Total gaussians');
% for ci = 1:Nchannels
%   fprintf(fid_Summary_gaussian,'%s,',['Gaussians within ' Experimental_channels{ci} ' channel']);
% end
% fprintf(fid_Summary_gaussian,'%s,\n','Shared Gaussians');
% fprintf(fid_Summary_gaussian,'%6.4f,',number_of_proteins);
% for ci = 1:Nchannels
%   fprintf(fid_Summary_gaussian,'%6.4f,',Unique_gaussians_in_eachchannel(ci));
% end
% fprintf(fid_Summary_gaussian,'%6.4f,\n',shared_gaussian_counter);



fid_summed_area1= fopen([datadir '/Summary_gaussian_trend_analysis_protein_replicate.csv'],'wt'); % create the output file with the header infromation
fprintf (fid_summed_area1,'%s,%s,%s,%s,%s,%s,%s\n',... %header for OutputGaus output
  'Number of Protein observed across replicates', 'No change- consistent across gaussians', 'Increase- consistent across gaussians',...
  'Decrease- consistent across gaussians','Increase- inconsistent across gaussians', 'Decrease- inconsistent across gaussians',...
  'Increase and Decrease observed in Gaussians'); %Write Header
fprintf (fid_summed_area1,'%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f\n',...
  NuniqueGauss,...
  No_change_consistent_across_gaus, Increase_consistent_across_gaus,...
  Decrease_consistent_across_gaus, Increase_inconsistent_across_gaus,...
  Decrease_inconsistent_across_gaus, Increase_and_decrease_across_gaus);
fclose(fid_summed_area1);


if 0
% #output
% write out table of master guassians list
fid_master_list= fopen([datadir 'Comparison/Master_guassian_list.csv'],'wt'); % create the output file with the header infromation
fprintf (fid_master_list,'%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n',... %header for OutputGaus output
  'Protein name', 'Unique_identifier (of best gaussian)','Replicate (of best gaussian)',...
  'Channel (of best gaussian)', 'Guassian_index_number (of best gaussian)',...
  'Center (of best gaussian)', 'Height (of best gaussian)', 'Width (of best gaussian)',...
  'SSE (of best gaussian)', 'adjrsquare (of best gaussian)','Gaussian Area (of best gaussian)','Complex Size (of best gaussian)'); %Write Header
for writeout_counter1= 1:length(Unique_protein_names)
  for jj = 1:nnz(Master_Gaussian_list.Center(writeout_counter1,:))
    fprintf(fid_master_list,'%s,%s,%6.3f,%s,%6.3f,%6.3f,%6.3f,%6.3f,%6.3f,%6.3f,%6.3f,%6.3f,\n',...
      Master_Gaussian_list.Protein_name{writeout_counter1},...
      Master_Gaussian_list.Unique_identifier{writeout_counter1,jj},...
      Master_Gaussian_list.Replicate(writeout_counter1,jj),...
      Master_Gaussian_list.Channel{writeout_counter1,jj},...
      Master_Gaussian_list.Guassian_index_number(writeout_counter1,jj),...
      Master_Gaussian_list.Center(writeout_counter1,jj),...
      Master_Gaussian_list.Height(writeout_counter1,jj),...
      Master_Gaussian_list.Width(writeout_counter1,jj),...
      Master_Gaussian_list.SSE(writeout_counter1,jj),...
      Master_Gaussian_list.adjrsquare(writeout_counter1,jj),...
      Master_Gaussian_list.Gaussian_area(writeout_counter1,jj),...
      Master_Gaussian_list.Complex_size(writeout_counter1,jj));
  end
end
fclose(fid_master_list);
end

if 0
% #output
% write out chromatograms
fid_master_chromatogram_list= fopen([datadir 'Comparison/Master_Chromatogram_list.csv'],'wt'); % create the output file with the header infromation
for writeout_counter1= 1:length(Unique_protein_names)
  for jj = 1:nnz(Master_Gaussian_list.Center(writeout_counter1,:))
    %write out Protein name and unique identifiers
    fprintf(fid_master_chromatogram_list,'%s,%6.4f,%s,',...
      Master_Gaussian_list.Unique_identifier{writeout_counter1},...
      Master_Gaussian_list.Guassian_index_number(writeout_counter1),...
      Master_Gaussian_list.Protein_name{writeout_counter1});
    
    %write out raw data to use for euclean distance
    fprintf(fid_master_chromatogram_list,'%6.4g,', Chromatograms(writeout_counter1,:));
    fprintf(fid_master_chromatogram_list,'\n');
  end
end
fclose(fid_master_chromatogram_list);
end

if 0
% #output
% write out table of master guassians list
fid_master_list1= fopen([datadir 'Comparison/Master_gaussian_list_fold_comparsion.csv'],'wt'); % create the output file with the header infromation
fprintf (fid_master_list1,'%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,',... %header for OutputGaus output
  'Protein name', 'Unique_identifier (of best gaussian)','Replicate (of best gaussian)',...
  'Channel (of best gaussian)', 'Guassian_index_number (of best gaussian)',...
  'Center (of best gaussian)', 'Height (of best gaussian)', 'Width (of best gaussian)',...
  'SSE (of best gaussian)', 'adjrsquare (of best gaussian)','Gaussian Area (of best gaussian)',...
  'Complex Size (of best gaussian)');
for ii = 1:replicate_num
  fprintf (fid_master_list1,'%s,',['Change observed replicate ' num2str(replicate_num)]);
end
fprintf(fid_master_list1,'%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n',...
  'Std Dev of fold change','Normalised fold change',...
  'Normalised fold change replicate 1','Normalised fold change replicate 2',...
  'Normalised fold change replicate 3','Normalised fold change replicate 4',...
  'Average fold change','Fold change replicate 1', 'Fold change replicate 2',...
  'Fold change replicate 3', 'Fold change replicate 4', 'p-value (ttest)',...
  'Below Adjusted_pvalue(bonferroni correction) (ttest)','p-value (MWW)',...
  'Below Adjusted_pvalue(bonferroni correction) (MWW)'); %Write Header
for writeout_counter1= 1:size(Finalised_Master_Gaussian_list.Center,1)
  for writeout_counter2= 1:nnz(Finalised_Master_Gaussian_list.Center(writeout_counter1,:))
    fprintf(fid_master_list1,'%s,%s,%6.3f,%s,%6.3f,%6.3f,%6.3f,%6.3f,%6.3f,%6.3f,%6.3f,%6.3f',...
      Finalised_Master_Gaussian_list.Protein_name{writeout_counter1},...
      Finalised_Master_Gaussian_list.Unique_identifier{writeout_counter1,writeout_counter2},...
      Finalised_Master_Gaussian_list.Replicate(writeout_counter1,writeout_counter2),...
      Finalised_Master_Gaussian_list.Channel{writeout_counter1,writeout_counter2},...
      Finalised_Master_Gaussian_list.Guassian_index_number(writeout_counter1,writeout_counter2),...
      Finalised_Master_Gaussian_list.Center(writeout_counter1,writeout_counter2),...
      Finalised_Master_Gaussian_list.Height(writeout_counter1,writeout_counter2),...
      Finalised_Master_Gaussian_list.Width(writeout_counter1,writeout_counter2),...
      Finalised_Master_Gaussian_list.SSE(writeout_counter1,writeout_counter2),...
      Finalised_Master_Gaussian_list.adjrsquare(writeout_counter1,writeout_counter2),...
      Finalised_Master_Gaussian_list.Gaussian_area(writeout_counter1,writeout_counter2),...
      Finalised_Master_Gaussian_list.Complex_size(writeout_counter1,writeout_counter2));
    for ii = 1:replicate_num
      fprintf(fid_master_list1,'%s',...
        Finalised_Master_Gaussian_list.foldLabel_byreplicate{writeout_counter1,writeout_counter2,ii});
    end
    fprintf(fid_master_list1,'%6.3f',...
      Finalised_Master_Gaussian_list.foldChange(writeout_counter1,writeout_counter2));
    for ii = 1:replicate_num
      fprintf(fid_master_list1,'%6.3f',...
        Finalised_Master_Gaussian_list.foldChange_byreplicate(writeout_counter1,writeout_counter2,ii));
    end
    fprintf(fid_master_list1,'%6.9f,%d,%6.9f,%d\n',...
      Finalised_Master_Gaussian_list.Ttest_p_values(writeout_counter1,writeout_counter2),...
      Finalised_Master_Gaussian_list.Satifies_Adjusted_pvalue(writeout_counter1,writeout_counter2),...
      Finalised_Master_Gaussian_list.MWW_p_values(writeout_counter1,writeout_counter2),...
      Finalised_Master_Gaussian_list.MWW_Satifies_Adjusted_pvalue(writeout_counter1,writeout_counter2));
    %Finalised_Master_Gaussian_list.Stdev_fold_change(writeout_counter1,writeout_counter2),...
    %Finalised_Master_Gaussian_list.Normalised_average_fold_change(writeout_counter1,writeout_counter2),...
    %Finalised_Master_Gaussian_list.normaliased_log2_comparsion_replicate_1(writeout_counter1,writeout_counter2),...
    %Finalised_Master_Gaussian_list.normaliased_log2_comparsion_replicate_2(writeout_counter1,writeout_counter2),...
    %Finalised_Master_Gaussian_list.normaliased_log2_comparsion_replicate_3(writeout_counter1,writeout_counter2),...
    %Finalised_Master_Gaussian_list.normaliased_log2_comparsion_replicate_4(writeout_counter1,writeout_counter2),...
  end
end
fclose(fid_master_list1);
end

if 0
%Write out a table of all T-test information
fid_ttest= fopen([datadir 'Comparison/Student_ttests_results.csv'],'wt'); % create the output file with the header infromation
fprintf (fid_ttest,'%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,\n',... %header for OutputGaus outpufid_master_list1= fopen('Master_guassian_list_fold_comparsion.csv','wt'); % create the output file with the header infromation
  'Protein name', 'Unique_identifier (of best gaussian)','Replicate (of best gaussian)',...
  'Channel (of best gaussian)', 'Guassian_index_number (of best gaussian)',...
  'Center (of best gaussian)', 'Height (of best gaussian)', 'Width (of best gaussian)',...
  'SSE (of best gaussian)', 'adjrsquare (of best gaussian)','Gaussian Area (of best gaussian)',...
  'Complex Size (of best gaussian)', 'Fold change replicate 1', 'Fold change replicate 2',...
  'Fold change replicate 3', 'Fold change replicate 4', 'p-value (ttest)','Std Dev of fold change',...
  'Number of observation', 'Degrees of freedom','Below Adjusted_pvalue '); %Write Header
for writeout_counter1= 1:size(Finalised_Master_Gaussian_list.Center,1)
  for writeout_counter2= 1:nnz(Finalised_Master_Gaussian_list.Center(writeout_counter1,:))
    fprintf(fid_ttest,'%s,%s,%6.3f,%s,%6.3f,%6.3f,%6.3f,%6.3f,%6.3f,%6.3f,%6.3f,%6.3f,%6.3f,%6.3f,%6.3f,%6.3f,%s\n',...
      Finalised_Master_Gaussian_list.Protein_name{writeout_counter1},...
      Finalised_Master_Gaussian_list.Unique_identifier{writeout_counter1,writeout_counter2},...
      Finalised_Master_Gaussian_list.Replicate(writeout_counter1,writeout_counter2),...
      Finalised_Master_Gaussian_list.Channel{writeout_counter1,writeout_counter2},...
      Finalised_Master_Gaussian_list.Guassian_index_number(writeout_counter1,writeout_counter2),...
      Finalised_Master_Gaussian_list.Center(writeout_counter1,writeout_counter2),...
      Finalised_Master_Gaussian_list.Height(writeout_counter1,writeout_counter2),...
      Finalised_Master_Gaussian_list.Width(writeout_counter1,writeout_counter2),...
      Finalised_Master_Gaussian_list.SSE(writeout_counter1,writeout_counter2),...
      Finalised_Master_Gaussian_list.adjrsquare(writeout_counter1,writeout_counter2),...
      Finalised_Master_Gaussian_list.Gaussian_area(writeout_counter1,writeout_counter2),...
      Finalised_Master_Gaussian_list.Complex_size(writeout_counter1,writeout_counter2),...
      Finalised_Master_Gaussian_list.Ttest_p_values(writeout_counter1,writeout_counter2),...
      Finalised_Master_Gaussian_list.Number_observation(writeout_counter1,writeout_counter2),...
      Finalised_Master_Gaussian_list.degree_freedom(writeout_counter1,writeout_counter2),...
      Finalised_Master_Gaussian_list.Satifies_Adjusted_pvalue(writeout_counter1,writeout_counter2));
    %     Finalised_Master_Gaussian_list.Stdev_fold_change(writeout_counter1,writeout_counter2),...
    %     Finalised_Master_Gaussian_list.log2_comparsion_replicate_1(writeout_counter1,writeout_counter2),...
    %     Finalised_Master_Gaussian_list.log2_comparsion_replicate_2(writeout_counter1,writeout_counter2),...
    %     Finalised_Master_Gaussian_list.log2_comparsion_replicate_3(writeout_counter1,writeout_counter2),...
    %     Finalised_Master_Gaussian_list.log2_comparsion_replicate_4(writeout_counter1,writeout_counter2),...
  end
end
fclose(fid_ttest);
end
%
% fid_summary_master_protein_comparsion1= fopen([datadir 'Comparison/Summary_changes_Protein_across_replicate.csv'],'wt'); % create the output file with the header infromation
% fprintf (fid_summary_master_protein_comparsion1,'%s,%s,%s,%s,%s\n',... %header for OutputGaus output
%   'Increase(in atleast two replicates)', 'Decrease (in atleast two replicates)', 'No change (in atleast two replicates)',...
%   '+/- (in atleast two replicates)', 'Inconsistent across replicates'); %Write Header
% fprintf (fid_summary_master_protein_comparsion1,'%6.4f,%6.4f,%6.4f,%6.4f,%6.4f\n',...
%   global_increase, global_decrease, global_no_change,...
%   global_increase_decrease, global_inconsistent_across_replicates);
% fclose(fid_summary_master_protein_comparsion1);
%
% fid_summary_master_comparsion1= fopen([datadir 'Comparison/Summary_changes_based_master_gaussian_list.csv'],'wt'); % create the output file with the header infromation
% fprintf (fid_summary_master_comparsion1,'%s,%s,%s,%s\n',... %header for OutputGaus output
%   'Increase(in atleast two replicates without observation of no changes)', 'Decrease (in atleast two replicates without observation of no changes)',...
%   'No change (in atleast two replicates)',...
%   'Inconsistent across replicates'); %Write Header
% fprintf (fid_summary_master_comparsion1,'%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f\n',...
%   sum(sum(Increase_change_across_replicates & ~(Decrease_change_across_replicates | No_change_across_replicates | Inconsistent_across_replicates))),...
%   sum(sum(Decrease_change_across_replicates & ~(Increase_change_across_replicates | No_change_across_replicates | Inconsistent_across_replicates))),...
%   sum(sum(No_change_across_replicates)),...
%   sum(sum(Inconsistent_across_replicates & ~(Increase_change_across_replicates | Decrease_change_across_replicates | No_change_across_replicates))));
% fclose(fid_summary_master_comparsion1);
%
% fid_summary_master_comparsion1= fopen([datadir 'Comparison/Summary_changes_based_master_gaussian_list_across_replicate_1.csv'],'wt'); % create the output file with the header infromation
% fprintf (fid_summary_master_comparsion1,'%s,%s,%s,%s,%s,%s\n',... %header for OutputGaus output
%   'Increase in replicate 1', 'Decrease in replicate 1', 'No change in replicate 1',...
%   'Unquantifiable observed only in MvsL channel replicate 1',...
%   'Unquantifiable observed only in HvsL channel replicate 1',...
%   'Unquantifiable not observed in replicate 1'); %Write Header
% fprintf (fid_summary_master_comparsion1,'%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f\n',...
%   Increase_counter_replicate_1, Decrease_counter_replicate_1,...
%   No_change_counter_replicate_1,Unquantifiable_observed_only_in_MvsL_channel_replicate_1,...
%   Unquantifiable_observed_only_in_HvsL_channel_replicate_1,...
%   Unquantifiable_Not_observed_in_replicate_replicate_1);
% fclose(fid_summary_master_comparsion1);
%
% fid_summary_master_comparsion2= fopen([datadir 'Comparison/Summary_changes_based_master_gaussian_list_across_replicate_2.csv'],'wt'); % create the output file with the header infromation
% fprintf (fid_summary_master_comparsion2,'%s,%s,%s,%s,%s,%s\n',... %header for OutputGaus output
%   'Increase in replicate 2', 'Decrease in replicate 2', 'No change in replicate 2',...
%   'Unquantifiable observed only in MvsL channel replicate 2',...
%   'Unquantifiable observed only in HvsL channel replicate 2',...
%   'Unquantifiable not observed in replicate 2'); %Write Header
% fprintf (fid_summary_master_comparsion2,'%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f\n',...
%   Increase_counter_replicate_2,Decrease_counter_replicate_2,...
%   No_change_counter_replicate_2,Unquantifiable_observed_only_in_MvsL_channel_replicate_2,...
%   Unquantifiable_observed_only_in_HvsL_channel_replicate_2,...
%   Unquantifiable_Not_observed_in_replicate_replicate_2);
% fclose(fid_summary_master_comparsion2);
%
% fid_summary_master_comparsion3= fopen([datadir 'Comparison/Summary_changes_based_master_gaussian_list_across_replicate_3.csv'],'wt'); % create the output file with the header infromation
% fprintf (fid_summary_master_comparsion3,'%s,%s,%s,%s,%s,%s\n',... %header for OutputGaus output
%   'Increase in replicate 3', 'Decrease in replicate 3', 'No change in replicate 3',...
%   'Unquantifiable observed only in MvsL channel replicate 3',...
%   'Unquantifiable observed only in HvsL channel replicate 3',...
%   'Unquantifiable not observed in replicate 3'); %Write Header
% fprintf (fid_summary_master_comparsion3,'%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f\n',...
%   Increase_counter_replicate_3,Decrease_counter_replicate_3,...
%   No_change_counter_replicate_3,Unquantifiable_observed_only_in_MvsL_channel_replicate_3,...
%   Unquantifiable_observed_only_in_HvsL_channel_replicate_3,...
%   Unquantifiable_Not_observed_in_replicate_replicate_3);
% fclose(fid_summary_master_comparsion3);
%
% fid_summary_master_comparsion4= fopen([datadir 'Comparison/Summary_changes_based_master_gaussian_list_across_replicate_4.csv'],'wt'); % create the output file with the header infromation
% fprintf (fid_summary_master_comparsion4,'%s,%s,%s,%s,%s,%s\n',... %header for OutputGaus output
%   'Increase in replicate 4', 'Decrease in replicate 4', 'No change in replicate 3',...
%   'Unquantifiable observed only in MvsL channel replicate 4',...
%   'Unquantifiable observed only in HvsL channel replicate 4',...
%   'Unquantifiable not observed in replicate 4'); %Write Header
% fprintf (fid_summary_master_comparsion4,'%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f\n',...
%   Increase_counter_replicate_4,Decrease_counter_replicate_4,...
%   No_change_counter_replicate_4,Unquantifiable_observed_only_in_MvsL_channel_replicate_4,...
%   Unquantifiable_observed_only_in_HvsL_channel_replicate_4,...
%   Unquantifiable_Not_observed_in_replicate_replicate_4);
% fclose(fid_summary_master_comparsion4);
%
% fid_summary_master_coverage= fopen([datadir 'Comparison/Summary_observed_protein_PCP_SILAC_coverage_within_experiments.csv'],'wt'); % create the output file with the header infromation
% fprintf (fid_summary_master_coverage,'%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,\n',... %header for OutputGaus output
%   'Replicate number','Isotopologue Channel',...
%   'Average PCP_SILAC coverage','Average coverage of the SEC', 'Median PCP_SILAC coverage',...
%   'Number of proteins with a coverage less then 0.5 ',...
%   'Number of proteins with a coverage less then 0.7',...
%   'Number of proteins with a coverage less then 0.85',...
%   'Number of proteins with a coverage less then 1',...
%   'Number of proteins with a coverage less then 1.5',...
%   'Number of proteins with a coverage less then 2',...
%   'Number of proteins with a coverage greater then 2',...
%   'Minimum coverage observed',...
%   'Maximum coverage observed'); %Write Header
% %Replicate 1 information
% %MvsL
% fprintf (fid_summary_master_coverage,'%s,%s,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,\n',...
%   'Replicate 1','MvsL',...
%   mean(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,1)),...
%   mean(Finalised_Master_Gaussian_list.SEC_coverageMvsL(:,1)),...
%   median(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,1)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,1)<=0.5)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,1)>=0)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,1)<=0.7)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,1)>=0.5)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,1)<=0.85)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,1)>=0.7)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,1)<=1)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,1)>=0.85)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,1)<=1.5)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,1)>=1)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,1)<=2)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,1)>=1.5)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,1)>=2)),...
%   min(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,1)),...
%   max(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,1)));
% %HvsL
% fprintf (fid_summary_master_coverage,'%s,%s,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,\n',...
%   'Replicate 1','HvsL',...
%   mean(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,1)),...
%   mean(Finalised_Master_Gaussian_list.SEC_coverageHvsL(:,1)),...
%   median(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,1)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,1)<=0.5)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,1)>=0)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,1)<=0.7)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,1)>=0.5)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,1)<=0.85)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,1)>=0.7)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,1)<=1)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,1)>=0.85)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,1)<=1.5)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,1)>=1)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,1)<=2)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,1)>=1.5)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,1)>=2)),...
%   min(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,1)),...
%   max(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,1)));
%
% %Replicate 2 information
% %MvsL
% fprintf (fid_summary_master_coverage,'%s,%s,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,\n',...
%   'Replicate 2','MvsL',...
%   mean(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,2)),...
%   mean(Finalised_Master_Gaussian_list.SEC_coverageMvsL(:,2)),...
%   median(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,2)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,2)<=0.5)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,2)>=0)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,2)<=0.7)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,2)>=0.5)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,2)<=0.85)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,2)>=0.7)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,2)<=1)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,2)>=0.85)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,2)<=1.5)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,2)>=1)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,2)<=2)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,2)>=1.5)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,2)>=2)),...
%   min(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,2)),...
%   max(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,2)));
% %HvsL
% fprintf (fid_summary_master_coverage,'%s,%s,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,\n',...
%   'Replicate 2','HvsL',...
%   mean(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,2)),...
%   mean(Finalised_Master_Gaussian_list.SEC_coverageHvsL(:,2)),...
%   median(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,2)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,2)<=0.5)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,2)>=0)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,2)<=0.7)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,2)>=0.5)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,2)<=0.85)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,2)>=0.7)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,2)<=1)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,2)>=0.85)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,2)<=1.5)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,2)>=1)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,2)<=2)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,2)>=1.5)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,2)>=2)),...
%   min(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,2)),...
%   max(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,2)));
%
%
% %Replicate 3 information
% %MvsL
% fprintf (fid_summary_master_coverage,'%s,%s,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,\n',...
%   'Replicate 3','MvsL',...
%   mean(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,3)),...
%   mean(Finalised_Master_Gaussian_list.SEC_coverageMvsL(:,3)),...
%   median(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,3)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,3)<=0.5)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,3)>=0)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,3)<=0.7)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,3)>=0.5)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,3)<=0.85)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,3)>=0.7)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,3)<=1)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,3)>=0.85)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,3)<=1.5)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,3)>=1)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,3)<=2)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,3)>=1.5)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,3)>=2)),...
%   min(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,3)),...
%   max(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,3)));
% %HvsL
% fprintf (fid_summary_master_coverage,'%s,%s,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,\n',...
%   'Replicate 3','HvsL',...
%   mean(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,3)),...
%   mean(Finalised_Master_Gaussian_list.SEC_coverageHvsL(:,3)),...
%   median(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,3)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,3)<=0.5)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,3)>=0)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,3)<=0.7)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,3)>=0.5)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,3)<=0.85)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,3)>=0.7)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,3)<=1)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,3)>=0.85)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,3)<=1.5)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,3)>=1)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,3)<=2)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,3)>=1.5)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,3)>=2)),...
%   min(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,3)),...
%   max(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,3)));
%
% %Replicate 4 information
% %MvsL
% fprintf (fid_summary_master_coverage,'%s,%s,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,\n',...
%   'Replicate 4','MvsL',...
%   mean(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,4)),...
%   mean(Finalised_Master_Gaussian_list.SEC_coverageMvsL(:,4)),...
%   median(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,4)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,4)<=0.5)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,4)>=0)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,4)<=0.7)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,4)>=0.5)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,4)<=0.85)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,4)>=0.7)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,4)<=1)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,4)>=0.85)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,4)<=1.5)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,4)>=1)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,4)<=2)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,4)>=1.5)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,4)>=2)),...
%   min(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,4)),...
%   max(Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(:,4)));
% %HvsL
% fprintf (fid_summary_master_coverage,'%s,%s,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,\n',...
%   'Replicate 4','HvsL',...
%   mean(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,4)),...
%   mean(Finalised_Master_Gaussian_list.SEC_coverageHvsL(:,4)),...
%   median(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,4)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,4)<=0.5)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,4)>=0)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,4)<=0.7)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,4)>=0.5)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,4)<=0.85)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,4)>=0.7)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,4)<=1)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,4)>=0.85)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,4)<=1.5)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,4)>=1)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,4)<=2)&(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,4)>=1.5)),...
%   sum((Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,4)>=2)),...
%   min(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,4)),...
%   max(Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(:,4)));
% %Close file
% fclose(fid_summary_master_coverage);
%
% fid_summary_protein_coverage= fopen([datadir 'Comparison/Summary_PCP_SILAC_coverage_Individual_proteins_within_experiments.csv'],'wt'); % create the output file with the header infromation
% fprintf (fid_summary_protein_coverage,'%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,\n',... %header for OutputGaus output
%   'Protein name','Summed isotopologue area MvsL replicate 1',...
%   'Summed isotopologue area MvsL replicate 2',...
%   'Summed isotopologue area MvsL replicate 3',...
%   'Summed isotopologue area MvsL replicate 4',...
%   'Summed isotopologue area HvsL replicate 1',...
%   'Summed isotopologue area HvsL replicate 2',...
%   'Summed isotopologue area HvsL replicate 3',...
%   'Summed isotopologue area HvsL replicate 4',...
%   'Summed isotopologue HvsM ratio replicate 1',...
%   'Summed isotopologue HvsM ratio replicate 2',...
%   'Summed isotopologue HvsM ratio replicate 3',...
%   'Summed isotopologue HvsM ratio replicate 4',...
%   'Number of Gaussians');
% for writeout_counter1= 1:Dimension_of_master_gaussian_list(1)
%   fprintf (fid_summary_protein_coverage,'%s,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,%6f,\n',...
%     Finalised_Master_Gaussian_list.Protein_name{writeout_counter1},...
%     Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(writeout_counter1,1),...
%     Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(writeout_counter1,2),...
%     Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(writeout_counter1,3),...
%     Finalised_Master_Gaussian_list.Summed_Gaussian_areaMvsL(writeout_counter1,4),...
%     Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(writeout_counter1,1),...
%     Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(writeout_counter1,2),...
%     Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(writeout_counter1,3),...
%     Finalised_Master_Gaussian_list.Summed_Gaussian_areaHvsL(writeout_counter1,4),...
%     Finalised_Master_Gaussian_list.Ratio_Gaussian_area(writeout_counter1,1),...
%     Finalised_Master_Gaussian_list.Ratio_Gaussian_area(writeout_counter1,2),...
%     Finalised_Master_Gaussian_list.Ratio_Gaussian_area(writeout_counter1,3),...
%     Finalised_Master_Gaussian_list.Ratio_Gaussian_area(writeout_counter1,4),...
%     nnz(Finalised_Master_Gaussian_list.Center(writeout_counter1,:)));
% end
% fclose(fid_summary_protein_coverage);
%
%
% fid_Quantation_numbers= fopen([datadir 'Comparison/Quantation_values_identified.csv'],'wt'); % create the output file with the header infromation
% fprintf (fid_Quantation_numbers,'%s,%s,%s,%s,%s\n',... %header for OutputGaus output
%   'Total number of values across replicates','Replicate 1',...
%   'Replicate 2','Replicate 3', 'Replicate 4'); %Write Header
% fprintf (fid_Quantation_numbers,'%6.4f,%6.4f,%6.4f,%6.4f,%6.4f\n',...
%   nnz(Finalised_Master_Gaussian_list.Center(:,:)),...
%   replicate_1_counter,replicate_2_counter,...
%   replicate_3_counter,replicate_4_counter);
% fclose(fid_Quantation_numbers);
%
% tt = toc;
% fprintf('  ...  %.2f seconds\n',tt)



%% Write out txt for Go enrichment
if 0
  %Aim: Write out file compatible with Perseus to rapidly allow the go
  %enrichment
  %Guassian level
  fid_Go_enrichment= fopen([datadir 'Comparison/Perseus_enrichment_Gaussian_level_file.csv'],'wt'); % create the output file with the header infromation
  fprintf (fid_Go_enrichment,'%s,%s,%s,',... %header for OutputGaus output
    'Center','Protein name','Normalised Average fold change');
  for ii = 1:Nchannels
    fprintf (fid_Go_enrichment,'%s,',['Normalised fold change replicate ' num2str(ii)]);
  end
  fprintf (fid_Go_enrichment,'%s,%s,%s,%s,%s,%s,\n',...
    'Increase (>= two replicates)', 'Decrease (>= two replicates)',...
    'p-value (t-test)','Below Adjusted_pvalue (bonferroni correction) (ttest)',...
    'p-value (MWW)','Below Adjusted_pvalue(bonferroni correction) (MWW)'); %Write Header
  
  for writeout_counter1= 1:size(Finalised_Master_Gaussian_list.Center,1)
    for writeout_counter2= 1:nnz(Finalised_Master_Gaussian_list.Center(writeout_counter1,:))
      fprintf(fid_Go_enrichment,'%6.3f,%s,%6.3f,',...
        Finalised_Master_Gaussian_list.Center(writeout_counter1,writeout_counter2),...
        Finalised_Master_Gaussian_list.Protein_name{writeout_counter1},...
        Finalised_Master_Gaussian_list.foldChange(writeout_counter1,writeout_counter2));
      %Finalised_Master_Gaussian_list.Stdev_fold_change(writeout_counter1,writeout_counter2))
      for ii = 1:replicate_num
        fprintf(fid_Go_enrichment,'%6.3f,',Finalised_Master_Gaussian_list.foldChange_byreplicate(writeout_counter1,writeout_counter2,ii));
      end
      fprintf(fid_Go_enrichment,'%s,%s,%6.9f,%d,%6.9f,%d,\n',...
        Finalised_Master_Gaussian_list.Increase_gauss_persaus_input{writeout_counter1,writeout_counter2},... % more than two replicates increase?
        Finalised_Master_Gaussian_list.Decrease_gauss_persaus_input{writeout_counter1,writeout_counter2},... % more than two replicates decrease?
        Finalised_Master_Gaussian_list.Ttest_p_values(writeout_counter1,writeout_counter2),...
        Finalised_Master_Gaussian_list.Satifies_Adjusted_pvalue(writeout_counter1,writeout_counter2),...
        Finalised_Master_Gaussian_list.MWW_p_values(writeout_counter1,writeout_counter2),...
        Finalised_Master_Gaussian_list.MWW_Satifies_Adjusted_pvalue(writeout_counter1,writeout_counter2));
    end
  end
  fclose(fid_Go_enrichment);
  
  
  %protein level
  fid_Go_enrichment= fopen([datadir 'Comparison/Perseus_enrichment_Protein_level_file.csv'],'wt'); % create the output file with the header infromation
  fprintf (fid_Go_enrichment,'%s,%s,%s,%s,%s,%s,\n',... %header for OutputGaus output
    'Protein name','Increase AND Decreases (>= two replicates)',...
    'Increase (>= two replicates)', 'Decrease (>= two replicates)',...
    'Gaussian fitted with change below adjusted_pvalue(bonferroni correction) (ttest)',...
    'Gaussian fitted with change below adjusted_pvalue(bonferroni correction) (MWW)');
  for writeout_counter1= 1:size(Finalised_Master_Gaussian_list.Center,1)
    fprintf(fid_Go_enrichment,'%s,%s,%s,%s,%s,%s,\n',...
      Finalised_Master_Gaussian_list.Protein_name{writeout_counter1},...
      Finalised_Master_Gaussian_list.Increase_and_Decrease_protein_persaus_input{writeout_counter1},...
      Finalised_Master_Gaussian_list.Increase_protein_persaus_input{writeout_counter1},...
      Finalised_Master_Gaussian_list.Decrease_protein_persaus_input{writeout_counter1},...
      Singficant_change_ttest_persaus_protein{writeout_counter1},...
      Singficant_change_mww_persaus_protein{writeout_counter1});
  end
  fclose(fid_Go_enrichment);
  
  tt = toc;
  tt = round(tt/10)*10;
  fprintf('  ...  %.2f seconds\n',tt)
  
end