%WRITEOUTPUT_INTERACTIONS Writes output tables for the PRINCE Interactions
%   module.



precision_write_out_counter = di;
Precision_values = desiredPrecision * 100;


%% Write out True interaction and summary lists for precision.


Final_Results_name=strcat(datadir,'Summary_Interactions_',mat2str(Precision_values(precision_write_out_counter)),'pc_replicate.csv');
fid_final= fopen(Final_Results_name,'wt'); % create the summary file of the interaction output
fprintf (fid_final,',%s,%s,%s,%s,%s,,,%s\n',... %header for OutputGaus output
  'Recall', 'Precision', 'Number of TP interactions','Number of FP interactions','Number of novel interactions',...
  'Number of possible interactions in CORUM');
fprintf (fid_final,'%s,%6.4f,%6.4f,%6.4f,%6.4f,%6.4f,,,%6.4f,\n',...
  'Assessed with global threshold',final_Recall(1), final_Precision(1), final_TP(1), final_FP(1), ...
  sum(interaction_final.global), all_positives);
if ~isempty(notes)
  fprintf (fid_final,'\n\n\n\n Notes:');
  for ii = 1:length(notes)
    fprintf (fid_final,'\n %s', notes{ii});
  end
end
fclose(fid_final);


% Final interactions list, and channel-specific final interactions
Final_list_Interactionsname=strcat(datadir,'Final_Interactions_list_',mat2str(Precision_values(precision_write_out_counter)),'_precision.csv');
fid_final_1 = fopen(Final_list_Interactionsname,'w');
fprintf (fid_final_1,'%s,%s,%s,%s,%s,%s,%s,%s,%s,\n',...
  'Unique interactions','Protein A','Protein B','Channel',...
  'Both proteins in Corum', 'Interaction in Corum','Interaction probability (avg.)',...
  'Interaction score (avg.)','Interaction score (condition-specific)'); %Write Header
fn = cell(1,length(user.silacratios));
fid = zeros(1,length(user.silacratios));
for ii = 1:length(user.silacratios)
  fn{ii} = strcat(datadir,'Final_Interactions_list_',user.silacratios{ii},'only_',mat2str(Precision_values(precision_write_out_counter)),'_precision.csv');
  fid(ii) = fopen(fn{ii},'w');
  fprintf (fid(ii),'%s,%s,%s,%s,%s,%s,%s,%s,%s,\n',...
    'Unique interactions','Protein A','Protein B','Channel',...
    'Both proteins in Corum', 'Interaction in Corum','Interaction probability (avg.)',...
    'Interaction score (avg.)','Interaction score (condition-specific)'); %Write Header
end
for ix=1:Total_unique_interactions
  fprintf(fid_final_1,'%s,%s,%s,%s,%d,%d,%6.4f,%6.4f,%s\n',...
    interaction_final.unique_interactions{ix},...
    interaction_final.proteinA{ix},...
    interaction_final.proteinB{ix},...
    interaction_final.channel_formatted{ix},...
    interaction_final.proteinInCorum(ix),...
    interaction_final.interactionInCorum(ix),...
    interaction_final.scoreavg(ix),...
    interaction_final.precisionDropoutavg(ix),...
    interaction_final.precisionDropout_formatted{ix});
  
  % channel-specific interactions list
  if length(interaction_final.channel{ix}) == 1
    chan = interaction_final.channel{ix};
    fprintf(fid(chan),'%s,%s,%s,%s,%d,%d,%6.4f,%6.4f,%s\n',...
      interaction_final.unique_interactions{ix},...
      interaction_final.proteinA{ix},...
      interaction_final.proteinB{ix},...
      interaction_final.channel_formatted{ix},...
      interaction_final.proteinInCorum(ix),...
      interaction_final.interactionInCorum(ix),...
      interaction_final.scoreavg(ix),...
      interaction_final.precisionDropoutavg(ix),...
      interaction_final.precisionDropout_formatted{ix});
  end
end
fclose(fid_final_1);


Final_Results_name=strcat(datadir,'Precision_across_channels.csv');
fid_final2= fopen(Final_Results_name,'wt'); % create the summary file of the interaction output
fprintf (fid_final2,'%s,%s,%s,%s,%s,%s,\n',... %header for OutputGaus output
  'Interaction observed in at least N conditions',...
  'Number of FP interactions',...
  'Number of TP interactions',...
  'Number of novel interactions',...
  'Number of total interactions',...
  'Precision %'); %Write Header
for precision_counter=1:(number_of_channels)
  fprintf (fid_final2,'%6f,%6f,%6f,%6f,%6f,%6f,\n',...
    precision_counter,...
    Precision_array(precision_counter,1),...
    Precision_array(precision_counter,2),...
    Precision_array(precision_counter,3),...
    sum(Precision_array(precision_counter,:)),...
    Precision_array(precision_counter,2) / (Precision_array(precision_counter,1) + Precision_array(precision_counter,2)));
end
% 
% fprintf(fid_final2,'\n\n\n\n');
% preci = 2;
% fprintf (fid_final2,'%s,,\n','Assessed with replicate-specific threshold');
% fprintf (fid_final2,'%s,%s,%s,%s,%s,%s,\n',... %header for OutputGaus output
%   'Interaction observed in at least N replicates',...
%   'Number of FP interactions',...
%   'Number of TP interactions',...
%   'Number of novel interactions',...
%   'Number of total interactions',...
%   'Precision %'); %Write Header
% for precision_counter=1:(number_of_replicates*number_of_channels)
%   fprintf (fid_final2,'%6f,%6f,%6f,%6f,%6f,%6f,\n',...
%     precision_counter,...
%     Precision_array{preci}(precision_counter,1),...
%     Precision_array{preci}(precision_counter,2),...
%     Precision_array{preci}(precision_counter,3),...
%     sum(Precision_array{preci}(precision_counter,:)),...
%     Precision_array{preci}(precision_counter,2) / (Precision_array{preci}(precision_counter,1) + Precision_array{preci}(precision_counter,2)));
% end
% fclose(fid_final2);





